(function(){
 const box=document.getElementById('v60-coach-chat'),input=document.getElementById('v60-coach-input'),send=document.getElementById('v60-coach-send'),mode=document.getElementById('v60-coach-mode'),lang=document.getElementById('v60-coach-lang');
 if(!box||!input||!send)return;
 const prompts={de:['Erzähle mir in 3–5 Sätzen, was du am Wochenende gemacht hast.','Was ist dir bei deiner Arbeit besonders wichtig und warum?','Beschreibe einen Ort, den du gern besuchen möchtest.'],en:['Tell me about a project you are proud of.','What makes a good team in your opinion?','Describe a place you would like to visit.'],fr:['Parle-moi de ton week-end en quelques phrases.','Qu’est-ce qui est important pour toi au travail ?','Décris un endroit que tu aimerais visiter.'],es:['Cuéntame qué hiciste el fin de semana.','¿Qué es importante para ti en el trabajo?','Describe un lugar que te gustaría visitar.'],it:['Raccontami cosa hai fatto nel fine settimana.','Che cosa è importante per te al lavoro?','Descrivi un posto che vorresti visitare.'],ru:['Расскажи, что ты делал на выходных.','Что для тебя важно в работе?','Опиши место, которое ты хотел бы посетить.'],pt:['Conta-me o que fizeste no fim de semana.','O que é importante para ti no trabalho?','Descreve um lugar que gostarias de visitar.']};
 const add=(txt,who='bot')=>{const d=document.createElement('div');d.className='v60-msg '+who;d.textContent=txt;box.appendChild(d);box.scrollTop=box.scrollHeight;};
 const localFeedback=(txt)=>{const words=txt.trim().split(/\s+/).filter(Boolean);let msg=words.length<8?'Guter Start. Versuche deine Antwort auf mindestens 3 vollständige Sätze zu erweitern.':'Gut – du produzierst zusammenhängenden Text. Lies deine Antwort noch einmal und prüfe Verbformen, Satzstellung und wiederkehrende Wörter.';if(/[.!?]$/.test(txt.trim())===false)msg+=' Achte außerdem auf vollständige Satzzeichen.';return msg;};
 const next=()=>{const arr=prompts[lang.value]||prompts.de;add(arr[Math.floor(Math.random()*arr.length)]);};
 async function submit(){const txt=input.value.trim();if(!txt)return;add(txt,'user');input.value='';send.disabled=true;const endpoint=(window.FW_SITE_CONFIG?.aiEndpoint||'').trim();if(endpoint){try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:txt,language:lang.value,mode:mode.value})});if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();add(j.reply||j.message||localFeedback(txt));}catch(e){add(localFeedback(txt)+' (Online-AI gerade nicht erreichbar – lokales Feedback verwendet.)');}}else add(localFeedback(txt));window.FW_TRACK?.('coach_message',{language:lang.value,mode:mode.value});send.disabled=false;setTimeout(next,500);}
 send.addEventListener('click',submit);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}});document.getElementById('v60-coach-new')?.addEventListener('click',next);next();
})();
