-- Sprachwerk v26 subscription + teacher schema
create table if not exists public.subscriptions (
 user_id uuid primary key references auth.users(id) on delete cascade,
 plan text not null default 'free' check (plan in ('free','pro','coaching')),
 status text not null default 'inactive',
 stripe_customer_id text,
 stripe_subscription_id text,
 current_period_end timestamptz,
 updated_at timestamptz not null default now()
);
create table if not exists public.teacher_students (
 id bigint generated by default as identity primary key,
 teacher_id uuid not null references auth.users(id) on delete cascade,
 student_id uuid not null references auth.users(id) on delete cascade,
 status text not null default 'active',
 created_at timestamptz not null default now(),
 unique(teacher_id,student_id)
);
create table if not exists public.assignments (
 id bigint generated by default as identity primary key,
 teacher_id uuid not null references auth.users(id) on delete cascade,
 student_id uuid not null references auth.users(id) on delete cascade,
 title text not null,
 description text,
 due_date date,
 status text not null default 'open',
 created_at timestamptz not null default now()
);
alter table public.subscriptions enable row level security;
alter table public.teacher_students enable row level security;
alter table public.assignments enable row level security;

create policy "subscription own read" on public.subscriptions for select to authenticated using ((select auth.uid())=user_id);
create policy "teacher relation read" on public.teacher_students for select to authenticated using ((select auth.uid())=teacher_id or (select auth.uid())=student_id);
create policy "assignment relation read" on public.assignments for select to authenticated using ((select auth.uid())=teacher_id or (select auth.uid())=student_id);
create policy "teacher assignment insert" on public.assignments for insert to authenticated with check ((select auth.uid())=teacher_id);
create policy "teacher assignment update" on public.assignments for update to authenticated using ((select auth.uid())=teacher_id) with check ((select auth.uid())=teacher_id);
